apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
{{ include "k8s-ecr-login-renew.podLabels" . | indent 12 }}
    spec:
      serviceAccountName: {{ include "k8s-ecr-login-renew.serviceAccount" . }}
      terminationGracePeriodSeconds: 0
      restartPolicy: Never
      containers:
      - name: k8s-ecr-login-renew
        imagePullPolicy: IfNotPresent
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ include "k8s-ecr-login-renew.secret" . }}
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "k8s-ecr-login-renew.secret" . }}
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: {{ include "k8s-ecr-login-renew.secret" . }}
                key: AWS_REGION
          - name: DOCKER_SECRET_NAME
            valueFrom:
              secretKeyRef:
                name: {{ include "k8s-ecr-login-renew.secret" . }}
                key: DOCKER_SECRET_NAME
{{- if .Values.overrideNamespace }}
          - name: TARGET_NAMESPACE
            valueFrom:
              secretKeyRef:
                name: {{ include "k8s-ecr-login-renew.secret" . }}
                key: TARGET_NAMESPACE
{{- else }}
          - name: TARGET_NAMESPACE
            value: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.ecr.dockerRegistries }}
          - name: DOCKER_REGISTRIES
            valueFrom:
              secretKeyRef:
                name: {{ include "k8s-ecr-login-renew.secret" . }}
                key: DOCKER_REGISTRIES
{{- end }}
